services:
  water-segmentation-api:
    build: .
    image: water-segmentation-api
    container_name: water-segmentation-api
    expose:
      - "8000"
    restart: unless-stopped

  water-segmentation-frontend:
    build: ./frontend
    image: water-segmentation-frontend
    container_name: water-segmentation-frontend
    ports:
      - "80:80"
    depends_on:
      - water-segmentation-api
    restart: unless-stopped
